"""Add mood and symptom_severity to reflections

Revision ID: 71267e3efd99
Revises: 
Create Date: 2026-03-24 19:37:58.183694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71267e3efd99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reflections', sa.Column('mood', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('reflections', sa.Column('symptom_severity', sa.Integer(), nullable=False, server_default='3'))

    op.alter_column('reflections', 'mood', server_default=None)
    op.alter_column('reflections', 'symptom_severity', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reflections', 'symptom_severity')
    op.drop_column('reflections', 'mood')
    # ### end Alembic commands ###
